# Default Configuration

spring:
  profiles:
    active: dev

  main:
    banner-mode: "off"

  jersey:
    servlet:
      load-on-startup: 1

  flyway:
    locations: "classpath:db/migrations"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  # TODO: check this stuff
  kafka:
    consumer:
      group-id: "playground_service"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            use.type.headers: false
            value.default.type: com.bellotapps.the_messenger.transport.json.jackson.JacksonMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add.type.headers: false


server:
  port: 8001
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
    include-exception: false
  servlet:
    context-path: /
  compression:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

executor-service:
  command-messages:
    sender: "PlaygroundService"
    request-execution:
      reply-channel: "PlaygroundService-Command-Replies"


---
# Configuration for Development Environment

spring:
  profiles:
    - dev
    - development

  datasource:
    url: jdbc:postgresql://localhost:5432/coding-eval-platform__playground-service
    username: coding-eval-platform__playground-service
    password: coding-eval-platform__playground-service

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # TODO: check this stuff
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"
---
# Configuration for Staging Environment

spring:
  profiles:
    - staging

---
# Configuration for Production Environment

spring:
  profiles:
    - prod
    - production
